# Generated by Django 5.0 on 2023-12-25 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2023, 12, 25, 11, 11, 5, 913673))),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
